title: Collaborate with others with Markdown and GitHub Pages
theme: minima
author: adityaoberai
email: aditya.oberai@studentambassadors.com
description: >
  This is a website for Microsoft Learn Student Ambassadors to work on in the "Collaborate with others with Markdown and GitHub Pages" workshop.
twitter_username: adityaoberai1
github_username:  adityaoberai